# Generated by Django 4.0 on 2022-04-17 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_coursepost_createdat'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('playlistId', models.CharField(max_length=200)),
                ('createdAt', models.DateField(auto_now=True)),
            ],
        ),
    ]
