# Generated by Django 4.0 on 2022-04-17 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_forgetpasswordtoken'),
        ('post', '0003_coursevideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevideo',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.course'),
        ),
    ]
