# Generated by Django 4.0 on 2022-04-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_coursevideo_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepost',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='CourseVideo',
        ),
    ]
