export const COURSE_LIST_REQUEST = 'COURSE_LIST_REQUEST'
export const COURSE_LIST_SUCCESS = 'COURSE_LIST_SUCCESS'
export const COURSE_LIST_FAIL = 'COURSE_LIST_FAIL'

export const COURSE_DETAILS_REQUEST = 'COURSE_DETAILS_REQUEST'
export const COURSE_DETAILS_SUCCESS = 'COURSE_DETAILS_SUCCESS'
export const COURSE_DETAILS_FAIL = 'COURSE_LIST_FAIL'

export const ENROLLED_COURSE_REQUEST = 'ENROLLED_COURSE_REQUEST'
export const ENROLLED_COURSE_SUCCESS = 'ENROLLED_COURSE_SUCCESS'
export const ENROLLED_COURSE_FAIL = 'ENROLLED_COURSE_FAIL'

export const COURSE_POSTS_REQUEST = 'COURSE_POSTS_REQEUST'
export const COURSE_POSTS_SUCCESS = 'COURSE_POSTS_SUCCESS'
export const COURSE_POSTS_FAIL = 'COURSE_POSTS_FAIL'

export const COURSE_CREATE_REVIEW_REQUEST = 'COURSE_CREATE_REVIEW_REQEUST'
export const COURSE_CREATE_REVIEW_SUCCESS = 'COURSE_CREATE_REVIEW_SUCCESS'
export const COURSE_CREATE_REVIEW_FAIL = 'COURSE_CREATE_REVIEW_FAIL'
export const COURSE_CREATE_REVIEW_RESET = 'COURSE_CREATE_REVIEW_RESET'