# Generated by Django 4.0 on 2022-01-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isInstructor',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='isStudent',
            field=models.BooleanField(default=False),
        ),
    ]
