# Generated by Django 4.0 on 2022-01-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_user_isinstructor_alter_user_isstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilePicture',
            field=models.ImageField(blank=True, default='logo.png', null=True, upload_to=''),
        ),
    ]
