# Generated by Django 4.0 on 2022-01-10 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_blog_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='requirments',
            new_name='requirements',
        ),
    ]
