# Generated by Django 4.0 on 2022-02-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_message_alter_blog_description_alter_blog_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledcourse',
            name='createdAt',
            field=models.DateField(auto_now=True),
        ),
    ]
