# Generated by Django 4.0 on 2022-02-25 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_enrolledcourse_createdat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
    ]
